config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  post "/homes/create", to: "homes#create"
  authenticated :user do
    resources :users 
    get '/projects/search', to: 'projects#search'
    get '/projects/search/pay', to: 'projects#search_pay'
    get '/projects/search/period', to: 'projects#search_period'
    get '/projects/search/method', to: 'projects#search_method'
    get '/projects/search/site', to: 'projects#search_site'
    get "/projects/how_to_use", to: "projects#how_to_use"
    resources :projects
    resources :orders
    root "projects#index"
  end
  get "/homes/forcom", to: "homes#forcom"
  get "/homes/sign_up", to: "homes#sign_up"
  root "homes#home"
end

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="fix navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "一覧", projects_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "案件検索", projects_search_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "プロフィール", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "案件獲得までの流れ", projects_how_to_use_path, class: "nav-link" %>
        </li>
        <li class="nav-item arrange-test">
          <%= link_to "アカウント編集", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item h4">
          <%= link_to "Home", "/", class: "nav-link ml-2" %>
        </li>
        <li class="nav-item float-left pt-1">
          <%= link_to "アカウント作成", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item pl-4 pt-1">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>