config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  post "/homes/create", to: "homes#create"
  authenticated :user do
    resources :users 
    get '/projects/search', to: 'projects#search'
    get '/projects/search/pay', to: 'projects#search_pay'
    get '/projects/search/period', to: 'projects#search_period'
    get '/projects/search/method', to: 'projects#search_method'
    get '/projects/search/site', to: 'projects#search_site'
    get "/projects/how_to_use", to: "projects#how_to_use"
    resources :projects
    resources :orders
    root "projects#index"
  end
  get "/homes/forcom", to: "homes#forcom"
  get "/homes/sign_up", to: "homes#sign_up"
  root "homes#home"
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
  validates :company_name, presence: true
  validates :pay, presence: true
  validates :period, presence: true
  validates :method, presence: true
  validates :cutback, presence: true
  validates :site, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_search, only: [:index, :search, :search_pay, :search_period, :search_method, :search_cutback, :search_site]

  def index
    # @projects = Project.page(params[:page]).per(6)
  end

  def search
  end

  def search_pay
  end

  def search_period
  end

  def search_method
  end


  def search_site
  end

  def show
    @project = Project.find(params[:id])
    if current_user.channel_follower.nil?
      redirect_to user_path(current_user)
    end
  end

  def how_to_use
  end

  private 
  
  def project_params
    params.require(:project).permit(:flag)
  end

  def set_search
    @q = Project.ransack(params[:q])
    @projects = @q.result.page(params[:page]).per(6)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/how_to_use.html.erb
<div class = "background-how_to_use">
<div class = "mask-how_to_use">
<div class = "container-fluid pt-5 ml-5">
<h1 class = "pt-2 mb-5 ml-5 font-img-bold">案件獲得までの大まかな流れ</h1>
  <ol>
    <div class = "row">
      <div class = "card col-5 ml-5 text-center">
        <div class = "card-body">
            <li class = "h4 pb-4 font-img">一覧画面から案件をチェックする。</li>
            <img class = "scale-how_to_use img-fluid rounded pl-5 position-how_to_use-4" src= "/assets/how_to_use1" alt="名前">
            <img class = "scale-how_to_use mx-auto position-how_to_use-2 img-fluid " src= "/assets/click-2.png" alt="名前">
        </div>
      </div>
      <div class = "card col-5 ml-5 text-center">
      <div class = "card-body">
        <li class = "h4 pb-4 font-img">案件詳細画面から募集ボタンを押す。</li>
        <img class = "scale-how_to_use img-fluid rounded position-how_to_use-5" src= "/assets/how_to_use2" alt="名前">
        <img class = "scale-how_to_use mx-auto position-how_to_use-3 img-fluid" src= "/assets/click-2.png" alt="名前">
      </div>
      </div>
    </div>
      <div class = "col-7 card mt-4 pb-0 d-flex align-items-center ml-4">
        <li class = "h4 font-img card-body ml-5">後は企業側の選考を待って、採用結果がメールで届く！</li>
      </div>
  </ol>
</div>
</div>
</div>

app/views/projects/index.html.erb
<div class = "background">
  <div class = "back-img3">
    <div class = "row mr-0">
      <% @projects.each do |project| %> 
        <div class = "card-deck mx-auto mt-5 mb-5">
          <div class = "card  bg-light col-11">
            <%= link_to image_tag("sample.jpg", width: '355', alt: "サンプル画像"), project_path(project.id), class: "card-img-top "%>
            <p class = "h3 pl-2 pt-2 text-left "><%= project.company_name %></p>
            <hr class = "mt-0 mb-0">
            <div class = "pl-2 pt-2 pr-3">
              <div class = "parent">
                <span class = "mb-1 text-left">報酬<span class = "ml-4">：¥<%= project.pay%></span></span>
                <span class = "text-right">期間 <span class = "padding-3">：<%= project.period%></span></span></span>
              </div>
              <div class = "parent">
                <span class = "mb-1 text-left">サイト<span class = "ml-2">：<%= project.site%></span></span>
                <span class = "text-right padding-2">広告方法<span class = "ml-3">：<%= project.method%></span></span>
              </div>
            </div>
            <hr class = "mt-0 ">
          </div>
        </div>
      <%end%>
    </div>
    <div class = "col-12 pt-5 pb-3">
      <p><%= paginate @projects%></p>
    </div>
  </div>
</div>

app/views/projects/search.html.erb
<div class = "back-img">
	<div class = "bkRGBA">
		<div class = "container pt-5">
		<h3 class = "display-4 arrange pl-3 text-center pb-2 pt-5"></h4>
			<div class = "back-img2 pb-2 pl-5 pt-5">
				<div class = "col-12 form-inline">
					<div class="form-group w-100 mt-3">
						<%= search_form_for @q, html: {class: "arrange-3"} do |f| %>
							<%= f.search_field :company_name_cont, class: "form-control w-75 bg-light" %>
							<%= f.submit '会社名で検索', class: "btn btn-secondary"%>
						<% end %>
					</div>
				</div>
				<div class = "pt-5 pl-5">
    			<%= link_to "会社名", projects_search_path, class: "w-20 btn btn-danger col-5 ml-5 mb-5 page-end"%>
					<%= link_to "支払い金額", projects_search_pay_path, class: "w-25 btn btn-secondary col-5 mb-5 page-end"%>
					<%= link_to "期間", projects_search_period_path, class: "w-25 btn btn-secondary col-5 mb-5 page-end"%>
				</div>
    			<%= link_to "広告方法", projects_search_method_path, class: "w-25 btn btn-secondary col-5 ml-5 mb-5 page-end"%>
					<%= link_to "対応サイト", projects_search_site_path, class: "w-20 btn btn-secondary col-5 mb-5 page-end"%>
			</div>
		</div>
	</div>
</div>

app/views/projects/search_method.html.erb
<div class = "back-img">
	<div class = "bkRGBA">
    <div class = "container pt-5">
    <h3 class = "display-4 arrange pl-3 text-center pb-2 pt-5"></h4>
      <div class = "back-img2 pb-2 pl-5 pt-5">
        <div class = "col-12 form-inline">
		      <div class="form-group w-100 mt-3">
				    <%= search_form_for @q, html: {class: "arrange-3"} do |f| %>
				      <%= f.search_field :method_cont, class: "form-control w-75 bg-light" %>
				      <%= f.submit '広告方法で検索', class: "btn btn-secondary"%>
				    <% end %>
          </div>
	      </div>
	      <div class = "pt-5 pl-5">
    			<%= link_to "会社名", projects_search_path, class: "w-25 btn btn-secondary col-5 ml-5 mb-5 page-end"%>
					<%= link_to "支払い金額", projects_search_pay_path, class: "w-25 btn btn-secondary col-5 mb-5 page-end"%>
					<%= link_to "期間", projects_search_period_path, class: "w-20 btn btn-secondary col-5 mb-5 page-end"%>
				</div>
    			<%= link_to "広告方法", projects_search_method_path, class: "w-20 btn btn-danger col-5 ml-5 mb-5 page-end"%>
					<%= link_to "対応サイト", projects_search_site_path, class: "w-25 btn btn-secondary col-5 mb-5 page-end"%>
			</div>
		</div>
	</div>
</div>

app/views/projects/search_pay.html.erb
<div class = "back-img">
	<div class = "bkRGBA">
		<div class = "container pt-5">
		<h3 class = "display-4 arrange pl-3 text-center pb-2 pt-5"></h4>
			<div class = "back-img2 pb-2 pl-5 pt-5">
				<div class = "col-12 form-inline">
					<div class="form-group w-100 mt-3">
						<%= search_form_for @q, html: {class: "arrange-3"} do |f| %>
							<%= f.search_field :pay_cont, class: "form-control w-75 bg-light" %>
							<%= f.submit '支払い金額で検索', class: "btn btn-secondary"%>
						<% end %>
					</div>
				</div>
				<div class = "pt-5 pl-5">
    			<%= link_to "会社名", projects_search_path, class: "w-25 btn btn-secondary col-5 ml-5 mb-5 page-end"%>
					<%= link_to "支払い金額", projects_search_pay_path, class: "w-20 btn btn-danger col-5 mb-5 page-end"%>
					<%= link_to "期間", projects_search_period_path, class: "w-25 btn btn-secondary col-5 mb-5 page-end"%>
				</div>
    			<%= link_to "広告方法", projects_search_method_path, class: "w-20 btn btn-secondary col-5 ml-5 mb-5 page-end"%>
					<%= link_to "対応サイト", projects_search_site_path, class: "w-25 btn btn-secondary col-5 mb-5 page-end"%>
			</div>
		</div>
	</div>
</div>

app/views/projects/search_period.html.erb
<div class = "back-img">
	<div class = "bkRGBA">
		<div class = "container pt-5">
		<h3 class = "display-4 arrange pl-3 text-center pb-2 pt-5"></h4>
			<div class = "back-img2 pb-2 pl-5 pt-5">
				<div class = "col-12 form-inline">
					<div class="form-group w-100 mt-3">
						<%= search_form_for @q, html: {class: "arrange-3"} do |f| %>
							<%= f.search_field :period_cont, class: "form-control w-75 bg-light" %>
							<%= f.submit '期間で検索', class: "btn btn-secondary"%>
						<% end %>
					</div>
				</div>
				<div class = "pt-5 pl-5">
    			<%= link_to "会社名", projects_search_path, class: "w-25 btn btn-secondary col-5 ml-5 mb-5 page-end"%>
					<%= link_to "支払い金額", projects_search_pay_path, class: "w-25 btn btn-secondary col-5 mb-5 page-end"%>
					<%= link_to "期間", projects_search_period_path, class: "w-20 btn btn-danger col-5 mb-5 page-end"%>
				</div>
    			<%= link_to "広告方法", projects_search_method_path, class: "w-20 btn btn-secondary col-5 ml-5 mb-5 page-end"%>
					<%= link_to "対応サイト", projects_search_site_path, class: "w-25 btn btn-secondary col-5 mb-5 page-end"%>
			</div>
		</div>
	</div>
</div>

app/views/projects/search_site.html.erb
<div class = "back-img">
	<div class = "bkRGBA">
    <div class = "container pt-5">
    <h3 class = "display-4 arrange pl-3 text-center pb-2 pt-5"></h4>
      <div class = "back-img2 pb-2 pl-5 pt-5">
        <div class = "col-12 form-inline">
		      <div class="form-group w-100 mt-3">
				    <%= search_form_for @q, html: {class: "arrange-3"} do |f| %>
				      <%= f.search_field :site_cont, class: "form-control w-75 bg-light" %>
				      <%= f.submit 'サイトで検索', class: "btn btn-secondary"%>
				    <% end %>
          </div>
	      </div>
	      <div class = "pt-5 pl-5">
    			<%= link_to "会社名", projects_search_path, class: "w-20 btn btn-secondary col-5 ml-5 mb-5 page-end"%>
					<%= link_to "支払い金額", projects_search_pay_path, class: "w-25 btn btn-secondary col-5 mb-5 page-end"%>
					<%= link_to "期間", projects_search_period_path, class: "w-25 btn btn-secondary col-5 mb-5 page-end"%>
				</div>
    			<%= link_to "広告方法", projects_search_method_path, class: "w-25 btn btn-secondary col-5 ml-5 mb-5 page-end"%>
					<%= link_to "対応サイト", projects_search_site_path, class: "w-20 btn btn-danger col-5 mb-5 page-end"%>
			</div>
		</div>
	</div>
</div>

app/views/projects/show.html.erb
<div class = "backimg-project-show-1">
  <div class = "container-fluid">
    <div class ="row">
      <div class = "col-7 ml-5">
        <div class = "pl-5">
          <h1 class = "pt-5 ml-5 pb-4 font-img-bold">案件情報一覧</h1>
          <div class = "row">
            <div class = "card col-3 text-center pt-3">
              <img class = "img-scale mx-auto" src= "/assets/company.png" alt="名前">
              <p class = "mb-0 mt-1 font-bold">"<%= @project.company_name %>"</p>
              <p>会社名</p>
            </div>
            <div class = "card col-3 text-center ml-5 pt-3">
              <img class = "img-scale mx-auto" src= "/assets/money.png" alt="名前">
              <p class = "mb-0 mt-1 font-bold">"¥<%= @project.pay %>"</p>
              <p>報酬金</p>
            </div>
            <div class = "card col-3 text-center ml-5 pt-3">
              <img class = "img-scale mx-auto" src= "/assets/time.png" alt="名前">
              <p class = "mb-0 mt-1 font-bold">"<%= @project.period %>"</p>
              <p>期間</p>
            </div>
          </div>
          <div class = "row mt-5">
            <div class = "card col-3 text-center pt-3">
              <img class = "img-scale mx-auto" src= "/assets/AD1.png" alt="名前">
              <p class = "mb-0 mt-1 font-bold">"<%= @project.method%>"</p>
              <p>広告方法</p>
            </div>
            <div class = "card col-3 text-center ml-5 pt-3">
              <img class = "img-scale mx-auto" src= "/assets/follower.png" alt="名前">
              <p class = "mb-0 mt-1 font-bold">"<%= @project.cutback %>人"</p>
              <p>必要知名度</p>
            </div>
            <div class = "card col-3 text-center ml-5 pt-3">
              <img class = "img-scale mx-auto" src= "/assets/WEB-small.png" alt="名前">
              <p class = "mb-0 mt-1 font-bold">"<%= @project.site %>"</p>
              <p>対象サイト</p>
            </div>
          </div>
          <div class = "card col-10 mt-5 ml-2 ">
          <div class = "row">
              <img class = "img-scale ml-5 pt-4 mb-4" src= "/assets/pen.png" alt="名前">
            <div class = "card-body">
              <p class = "text-center mr-5 pr-5">その他</p>
              <p class = "mb-0 mt-1 font-bold text-center mr-5 pr-5">"<%= @project.description %>"</p>
            </div>
            </div>
          </div>
        </div>
        <% if current_user.active_site == @project.site%>
          <div class = "col-10 ml-3 mt-5">
            <% if Order.find_by(user_id: current_user.id, project_id: @project.id)%>
              <%= link_to "あなたはこの案件に応募しています", project_path(@project), class: "btn btn-danger"%>
            <% else %>
              <% if @project.cutback < current_user.channel_follower %>
                <div>
                  <%= link_to "この案件を受ける", orders_path(@project), method: :post, class: "btn btn-success btn-lg mb-5" %>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class = "col-4 font-img">
        <h1 class = "pt-5 pb-3 font-img-bold">応募者一覧</h1>
        <% @project.users.each do |person|%>
          <hr class = "backimg-show">
          <div class = "parent mt-2 ml-2 mr-2">
            <span class = "text-left">名前 : <%= person.stage_name %></span>
            <span class = "text-right">チャンネル名 :<%= person.channel_name %></span>
          </div>
          <div class = "parent pt-3 ml-2 mr-2">
            <span class = "text-left mt-1">チャンネル登録者数 : <%= person.channel_follower %></span>
            <%= link_to "詳細はこちら", user_path(person.id), class: "btn btn-secondary btn-sm"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>